FROM node:18-alpine

WORKDIR /app

COPY apps/api/package*.json ./
RUN npm install

COPY apps/api/src ./src
COPY apps/api/tsconfig.json ./
COPY apps/api/package.json ./

RUN npm run build

EXPOSE 8080

# Force the port via environment variable
ENV PORT=8080

CMD ["npm", "start"]
